name: CI/CD Pipeline for Errand Service

# Trigger this workflow on push to main branch or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner

    env:
      DOCKER_IMAGE: your-dockerhub-username/errand-service  # Replace with your Docker Hub username
      DOCKER_TAG: ${{ github.sha }}  # Use commit SHA as tag

    steps:
      # --------------------------
      # Step 1: Checkout repository
      # --------------------------
      - name: Checkout code
        uses: actions/checkout@v3

      # --------------------------
      # Step 2: Set up JDK 21
      # --------------------------
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # --------------------------
      # Step 3: Build the project with Maven
      # --------------------------
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # --------------------------
      # Step 4: Log in to Docker Hub
      # --------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Add in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Add in GitHub Secrets

      # --------------------------
      # Step 5: Build Docker image
      # --------------------------
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE:$DOCKER_TAG .

      # --------------------------
      # Step 6: Push Docker image to Docker Hub
      # --------------------------
      - name: Push Docker image
        run: docker push $DOCKER_IMAGE:$DOCKER_TAG

      # --------------------------
      # Optional Step 7: Tag 'latest' and push
      # --------------------------
      - name: Push 'latest' tag
        run: |
          docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:latest
