name: CI/CD Pipeline for Errand Service

# Trigger pull requests and pushes to main
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  # --------------------------
  # Job 1: Build for PRs (no secrets)
  # --------------------------
  build-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn clean package -DskipTests

  # --------------------------
  # Job 2: Build and deploy for main pushes (secrets required)
  # --------------------------
  build-and-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: sangurakoded/errand-service
      DOCKER_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn clean package -DskipTests

      # --------------------------
      # Verify Docker secrets exist (fail fast)
      # --------------------------
      - name: Check Docker secrets
        run: |
          if [[ -z "${{ secrets.DOCKER_HUB_USERNAME }}" || -z "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" ]]; then
            echo "ERROR: Docker Hub secrets are missing! Please add DOCKER_HUB_USERNAME and DOCKER_HUB_ACCESS_TOKEN in Actions secrets."
            exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE:$DOCKER_TAG .

      - name: Push Docker image (commit tag)
        run: docker push $DOCKER_IMAGE:$DOCKER_TAG

      - name: Push latest tag
        run: |
          docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:latest
