name: EasyErrands CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code (with submodules)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2. Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Run tests
      - name: Run Maven tests
        run: mvn clean test --file pom.xml

      # 4. Build Docker images for each service
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Images
        run: |
          SERVICES=("api-gateway" "assignment-service" "auth-service" "errand-service" "tracking-service" "config-server" "discovery-service")
          for SERVICE in "${SERVICES[@]}"; do
            echo "🚀 Building $SERVICE"
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE:latest $SERVICE/
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$SERVICE:latest
          done

      # 5. (Optional) Deploy to server/K8s
      # Add SSH deploy or kubectl apply steps here later
